<?php
use Magento\Framework\Escaper;
use Maisondunet\SaveQuote\ViewModel\CurrentCart;

/**
 * @var $block CurrentCart
 * @var $escaper Escaper
 */
?>
<form  method="post" action="<?= $escaper->escapeUrl($block->getUrl('mdnsavecart/customer/save'))?>">
    <span><?= __("Name") ?></span>
    <input type="text" name="name" required>
    <span><?= __("Description") ?></span>
    <input type="text" name="description">
    <?= $block->getChildHtml("form_additional_field") ?>
    <button type="submit"><?= __("Save your cart") ?></button>
</form>
